import Config

config :core,
  signing_salt: System.get_env("SIGNING_SALT"),
  domain: "www-malf-me.fly.dev",
  base_url: "https://www-malf-me.fly.dev/",
  production: true

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :core, CoreWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Core.Finch

# Do not print debug messages in production
config :logger,
  level: :info,
  backends: [:console, Sentry.LoggerBackend]

config :oban, log_level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
